
[package]
name = "forge-lint"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
solar-parse.workspace = true
solar-ast.workspace = true
solar-interface.workspace = true
eyre.workspace = true
regex = "1.11"
clap = { version = "4", features = ["derive"] }
