name: Foundry Benchmarks

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number to comment on (optional)"
        required: false
        type: string
      versions:
        description: "Comma-separated list of Foundry versions to benchmark (e.g., stable,nightly,v1.0.0)"
        required: false
        type: string
        default: "stable,nightly"
      repos:
        description: "Comma-separated list of repos to benchmark (e.g., ithacaxyz/account:main,Vectorized/solady)"
        required: false
        type: string
      benchmarks:
        description: "Comma-separated list of benchmarks to run (forge_test,forge_build_no_cache,forge_build_with_cache)"
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  benchmark:
    name: Run Foundry Benchmarks
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            ./

      - name: Install foundryup
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          echo "$HOME/.foundry/bin" >> $GITHUB_PATH

      - name: Build benchmark binary
        run: cargo build --release --bin foundry-bench

      - name: Run benchmarks
        run: |
          VERSIONS="${{ github.event.inputs.versions || 'stable,nightly' }}"
          REPOS="${{ github.event.inputs.repos }}"
          BENCHMARKS="${{ github.event.inputs.benchmarks }}"

          # Build the command with force-install for CI
          CMD="./target/release/foundry-bench --output-dir ./benches --force-install"

          # Add versions
          CMD="$CMD --versions $VERSIONS"

          # Add repos if specified
          if [ -n "$REPOS" ]; then
            CMD="$CMD --repos $REPOS"
          fi

          # Add benchmarks if specified
          if [ -n "$BENCHMARKS" ]; then
            CMD="$CMD --benchmarks $BENCHMARKS"
          fi

          echo "Running: $CMD"
          $CMD

      - name: Commit benchmark results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add benches/LATEST.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(`benches`): update benchmark results

            🤖 Generated with [Foundry Benchmarks](https://github.com/${{ github.repository }}/actions)
            
            Co-Authored-By: github-actions <github-actions@github.com>"
            git push
          fi

      - name: Read benchmark results
        id: benchmark_results
        run: |
          if [ -f "benches/LATEST.md" ]; then
            {
              echo 'results<<EOF'
              cat benches/LATEST.md
              echo 'EOF'
            } >> $GITHUB_OUTPUT
          else
            echo 'results=No benchmark results found.' >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR
        if: github.event.inputs.pr_number != ''
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ github.event.inputs.pr_number }};
            const benchmarkResults = `${{ steps.benchmark_results.outputs.results }}`;

            const comment = `## 📊 Foundry Benchmark Results

            <details>
            <summary>Click to view detailed benchmark results</summary>

            ${benchmarkResults}

            </details>

            ---

            🤖 This comment was automatically generated by the [Foundry Benchmarks workflow](https://github.com/${{ github.repository }}/actions).

            To run benchmarks manually: Go to [Actions](https://github.com/${{ github.repository }}/actions/workflows/foundry-benchmarks.yml) → "Run workflow"`;

            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
