name: Foundry Benchmarks

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number to comment on (optional)"
        required: false
        type: string
      versions:
        description: "Comma-separated list of Foundry versions to benchmark (e.g., stable,nightly,v1.0.0)"
        required: false
        type: string
        default: "stable,nightly"
      repos:
        description: "Comma-separated list of repos to benchmark (e.g., ithacaxyz/account:main,Vectorized/solady)"
        required: false
        type: string
        default: "ithacaxyz/account:v0.3.2,Vectorized/solady:v0.1.22"

permissions:
  contents: write
  pull-requests: write

jobs:
  setup:
    name: Setup and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            ./

      - name: Setup Foundry
        run: |
          ./.github/scripts/setup-foundryup.sh
          echo "$HOME/.foundry/bin" >> $GITHUB_PATH

      - name: Install hyperfine
        run: |
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.19.0/hyperfine_1.19.0_amd64.deb
          sudo dpkg -i hyperfine_1.19.0_amd64.deb

      - name: Build benchmark binary
        run: cargo build --release --bin foundry-bench

      - name: Upload benchmark binary
        uses: actions/upload-artifact@v4
        with:
          name: foundry-bench
          path: target/release/foundry-bench

  forge-test-bench:
    name: Forge Test Benchmarks
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Foundry
        run: |
          ./.github/scripts/setup-foundryup.sh
          echo "$HOME/.foundry/bin" >> $GITHUB_PATH

      - name: Install hyperfine
        run: |
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.19.0/hyperfine_1.19.0_amd64.deb
          sudo dpkg -i hyperfine_1.19.0_amd64.deb

      - name: Download benchmark binary
        uses: actions/download-artifact@v4
        with:
          name: foundry-bench

      - name: Make binary executable
        run: chmod +x foundry-bench

      - name: Run forge test benchmarks
        run: |
          VERSIONS="${{ github.event.inputs.versions || 'stable,nightly' }}"
          REPOS="${{ github.event.inputs.repos || 'ithacaxyz/account:v0.3.2,Vectorized/solady:v0.1.22' }}"

          ./foundry-bench --output-dir ./benches --force-install \
            --versions $VERSIONS \
            --repos $REPOS \
            --benchmarks forge_test,forge_fuzz_test \
            --output-file forge_test_bench.md

      - name: Upload test benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: forge-test-results
          path: benches/forge_test_bench.md

  forge-build-bench:
    name: Forge Build Benchmarks
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Foundry
        run: |
          ./.github/scripts/setup-foundryup.sh
          echo "$HOME/.foundry/bin" >> $GITHUB_PATH

      - name: Install hyperfine
        run: |
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.19.0/hyperfine_1.19.0_amd64.deb
          sudo dpkg -i hyperfine_1.19.0_amd64.deb

      - name: Download benchmark binary
        uses: actions/download-artifact@v4
        with:
          name: foundry-bench

      - name: Make binary executable
        run: chmod +x foundry-bench

      - name: Run forge build benchmarks
        run: |
          VERSIONS="${{ github.event.inputs.versions || 'stable,nightly' }}"
          REPOS="${{ github.event.inputs.repos || 'ithacaxyz/account:v0.3.2,Vectorized/solady:v0.1.22' }}"

          ./foundry-bench --output-dir ./benches --force-install \
            --versions $VERSIONS \
            --repos $REPOS \
            --benchmarks forge_build_no_cache,forge_build_with_cache \
            --output-file forge_build_bench.md

      - name: Upload build benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: forge-build-results
          path: benches/forge_build_bench.md

  forge-coverage-bench:
    name: Forge Coverage Benchmarks
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Foundry
        run: |
          ./.github/scripts/setup-foundryup.sh
          echo "$HOME/.foundry/bin" >> $GITHUB_PATH

      - name: Install hyperfine
        run: |
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.19.0/hyperfine_1.19.0_amd64.deb
          sudo dpkg -i hyperfine_1.19.0_amd64.deb

      - name: Download benchmark binary
        uses: actions/download-artifact@v4
        with:
          name: foundry-bench

      - name: Make binary executable
        run: chmod +x foundry-bench

      - name: Run forge coverage benchmarks
        run: |
          VERSIONS="${{ github.event.inputs.versions || 'stable,nightly' }}"
          # Coverage only runs on ithacaxyz/account:v0.3.2

          ./foundry-bench --output-dir ./benches --force-install \
            --versions $VERSIONS \
            --repos ithacaxyz/account:v0.3.2 \
            --benchmarks forge_coverage \
            --output-file forge_coverage_bench.md

      - name: Upload coverage benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: forge-coverage-results
          path: benches/forge_coverage_bench.md

  combine-results:
    name: Combine and Publish Results
    needs: [forge-test-bench, forge-build-bench, forge-coverage-bench]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all benchmark results
        uses: actions/download-artifact@v4
        with:
          pattern: forge-*-results
          path: benches/
          merge-multiple: true

      - name: Combine benchmark results
        run: ./.github/scripts/combine-benchmarks.sh benches

      - name: Commit and read benchmark results
        id: benchmark_results
        run: ./.github/scripts/commit-and-read-benchmarks.sh benches "${{ github.event_name }}" "${{ github.repository }}"

      - name: Comment on PR
        if: github.event.inputs.pr_number != '' || github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ github.event.inputs.pr_number || github.event.pull_request.number }};
            const benchmarkResults = `${{ steps.benchmark_results.outputs.results }}`;

            const comment = `## 📊 Foundry Benchmark Results

            <details>
            <summary>Click to view detailed benchmark results</summary>

            ${benchmarkResults}

            </details>

            ---

            🤖 This comment was automatically generated by the [Foundry Benchmarks workflow](https://github.com/${{ github.repository }}/actions).

            To run benchmarks manually: Go to [Actions](https://github.com/${{ github.repository }}/actions/workflows/benchmarks.yml) → "Run workflow"`;

            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
